strategies:
  - tool_name: exa_search
    tool_params:
      category: news
    input_format: "{{text}}"
    output_name: exa_news_result
  - tool_name: exa_search
    tool_params:
      category: tweet
    input_format: "{{text}}"
    output_name: exa_tweet_result
  - model: openrouter/openai/o1-preview
    prompt_name: beta_material_to_blog
    input_format: |
      user input text:
      {{exa_news_result}}a
      {{exa_tweet_result}}
      blog example:
      {{memory_blog_example}}
    output_name: tech_blog_draft

